# Generated by Django 5.2.7 on 2025-11-03 18:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Tag name (e.g., 'Science Fiction')", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text="URL-friendly version (e.g., 'science-fiction')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Tag description', null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Author's First Name.", max_length=100)),
                ('last_name', models.CharField(help_text="Author's Last Name.", max_length=100)),
                ('date_of_birth', models.DateField(blank=True, help_text="Author's Date of Birth(optiona)", null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('first_name', 'last_name', 'date_of_birth')},
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Book title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Book description', null=True)),
                ('isbn', models.CharField(help_text='ISBN number', max_length=13, unique=True)),
                ('published_date', models.DateField(blank=True, help_text='Publication date', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata for this book', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(help_text='Authors who wrote this book', related_name='books', to='catalog.author')),
                ('tags', models.ManyToManyField(blank=True, help_text='ategories/genres for this book', related_name='books', to='catalog.tag')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(help_text='Unique barcode for this copy', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed'), ('damaged', 'Damaged'), ('lost', 'Lost')], default='available', help_text='Current status of this copy', max_length=20)),
                ('checkout_date', models.DateField(blank=True, help_text='Date this copy was checked out', null=True)),
                ('due_date', models.DateField(blank=True, help_text='Date this copy is due back', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(help_text='Book this copy belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='catalog.book')),
            ],
            options={
                'verbose_name_plural': 'copies',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_at', models.DateTimeField(auto_now_add=True, help_text='Date this loan was created')),
                ('due_back', models.DateField(help_text='Date this loan is due back')),
                ('returned_at', models.DateTimeField(blank=True, help_text='Date this loan was returned', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('copy', models.ForeignKey(help_text='Copy this loan belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='catalog.copy')),
                ('user', models.ForeignKey(help_text='User this loan belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-borrowed_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('returned_at', None)), fields=('copy',), name='only_one_active_loan_per_copy')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Rating (1-5 stars)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Review comment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(help_text='Book this review belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.book')),
                ('user', models.ForeignKey(help_text='User who wrote this review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['book'], name='catalog_rev_book_id_609aa7_idx')],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
